services:
    nopcommerce_web:
        build: .
        container_name: nopcommerce
        ports:
            - "80:80"
        environment:
            OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
            OTEL_SERVICE_NAME: "nopcommerce"
        depends_on:
            - nopcommerce_database
            - otel-collector
    nopcommerce_database:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        container_name: nopcommerce_mssql_server
        environment:
            SA_PASSWORD: "nopCommerce_db_password"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"

    otel-collector:
        image: otel/opentelemetry-collector-contrib:latest
        container_name: otel-collector
        volumes:
            - ./infra/otel-collector/config.yaml:/etc/otelcol-contrib/config.yaml
        ports:
            - "4317:4317"
            - "4318:4318"
            - "8889:8889"
        depends_on:
            - jaeger

    jaeger:
        image: jaegertracing/all-in-one:latest
        container_name: jaeger
        environment:
            COLLECTOR_OTLP_ENABLED: "true"
        ports:
            - "16686:16686"
            - "4317"

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        volumes:
            - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"
        depends_on:
            - otel-collector

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        volumes:
            - ./infra/grafana/provisioning:/etc/grafana/provisioning
        ports:
            - "3000:3000"
        depends_on:
            - prometheus
            - jaeger

volumes:
  nopcommerce_data:            