receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  attributes/sanitize:
    actions:
      - key: client.address
        action: delete
      - key: net.peer.ip
        action: delete
      - key: http.request.header.cookie
        action: delete

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes/sanitize]
      exporters: [otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [attributes/sanitize]
      exporters: [prometheus]
